#!/bin/sh

set -e

case "$1" in
    configure)
        pam-auth-update --package
    ;;

    abort-upgrade|abort-deconfigure|abort-remove)
    ;;

    *)
    echo "$0 called with unknown argument \`$1'" 1>&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
